export { Lexer, tokenize } from "./lexer.js"
export { Parser, parse } from "./parser.js"
export { NodeKind, make, isNode, walk } from "./ast.js"
export { Token, TokenKind, TokenCursor, KEYWORDS, KEYWORD_VALUES } from "./contracts/tokens.js"
export { Diagnostic, DiagnosticBag, DiagnosticSeverity, SourceLocation, SourceSpan } from "./contracts/diagnostics.js"
export { Type, TypeKind, NumericKind, BUILTIN_TYPES, narrowestIntegerType, valueRange, promotedNumericType, rangeForType, canOverflow } from "./types.js"
export { Symbol, Scope, TypeInferrer } from "./analyzer.js"
export { compile, CompilationResult } from "./compile.js"
export { CodeGenerator, generateC } from "./codegen.js"
export { ResourceAnalyzer, ResourceBudget, SceneResources, AssetResources, HARDWARE_BUDGETS, formatBytes } from "./resources.js"
export { Tile, TileDeduplicator, deduplicateTiles, reverseBits, tileBytes, savedBytes } from "./tiles.js"
export { BuildReport } from "./report.js"
export { rgb555, unpack555, collectUniqueColors, quantizePalette, groupSharedPalette, paletteDeltaE, colorError, paletteBytes } from "./palette.js"
export { BitmapImage, extractTiles, pixelsToIndices, indicesToBitplanes, tileToBitplanes, bitplaneByteCount } from "./bitmap.js"
export { decodePng, PngDecodeError } from "./png.js"
export { fixed, toFloat, mulFixed, divFixed, lerp, TrigTable, DeterministicRandom, Mathx, Trig, FIXED_SCALE } from "./fixed_math.js"
export { SourceMapEntry, SourceMapGenerator, buildSourceMap } from "./sourcemap.js"
export { SaveSchema, SaveData, serializeSave, deserializeSave, checksum16, migrateSave } from "./save.js"
export { FixedArray, Pool, RingBuffer, BitSet, Queue } from "./containers.js"
export { Aabb, aabbOverlap, pointInAabb, GridBroadphase, TileCollision } from "./collision.js"
export { AssetCompiler, CompiledSpriteAsset, compileSpriteAsset } from "./asset_compiler.js"
export { RomPlanner, RomLayout, RomBank, chooseRomMapping } from "./rom.js"
